let _ = require('lodash')

const prefixes = [
  'Shimmering', 'Shining', 'Dark', 'Light', 'Spiked', 'Dull', 'Rough',
  'Tarnished', 'Old', 'New', 'Cracked', 'Damaged', 'Superb', 'Superior',
  'Inferior', 'Ethereal', 'Buzzing', 'Glowing', 'Humming', 'Gossamer',
  'Eternal', 'Barbed', 'Demonic', 'Smooth', 'Pockmarked', 'Elite', 'Damned',
  'Blessed', 'Cursed', 'Accursed', 'Twisted', 'Carved', 'Runed', 'Thin',
  'Thick', 'Soft', 'Hard', 'Blackened', 'Cold', 'Warm', 'Freezing', 'Hot',
  'Pure', 'Holy', 'Unholy', 'Corrupted', 'Emblazoned', 'Heraldric',
  'Sparkling', 'Sparking', 'Coruscating', 'Translucent', 'Shadowy',
  'Glistening', 'Abyssal', 'Ornate', 'Amazing', 'Enchanted', 'Etched',
  'Focused', 'Crafted', 'Harmonious', 'Discordant', 'Fine', 'Great',
  'Glimmering', 'Polished', 'Howling', 'Exquisite', 'Tempered', 'Elemental',
  'Primal', 'Righteous', 'Peerless', 'Worked', 'Dusty', 'Frosted', 'Faded',
  'Worn', 'Pitted', 'Magnificent', 'Twilight', 'Eldritch', 'Icy', 'Frigid',
  'Soft', 'Frost', 'Ragged', 'Braided', 'Wizards', 'Gleaming', 'Glinting',
  'Decorated', 'Dirty', 'Bloodstained', 'Bloody', 'Screaming', 'Furious',
  'Reinforced', 'Rugged', 'Cold', 'Feral', 'Fierce', 'Flayed', 'Finespun',
  'Hardened', 'Honorable', 'Imbued', 'Luminous', 'Luminescent', 'Lupine',
  'Matchless', 'Mischevous', 'Radiant', 'Radiating', 'Softened', 'Raw',
  'Refined', 'Totemic', 'Imperial', 'Fathomless', 'Sinister', 'Silvered',
  'Gilded', 'Spectral', 'Ghostly', 'Rich', 'Well', -'Designed', 'Druidic',
  'Hierophantic', 'Lucky', 'Runic', 'Juggernaut', 'Infernal', 'Adorned',
  'Wicked', 'Grand', 'Aged', 'Shaped', 'Twisted', 'Arcane', 'Warshadow',
  'Glimmerspirit', 'Darkened', 'Regal', 'Sturdy', 'Spider', 'Wolf', 'Mottled',
  'Scarred', 'Blackthorn', 'Thorned', 'Resonant', 'Lavish', 'Splendid',
  'Dread', 'Valorous', 'Ensorcelled', 'Crested', 'Embossed',
]

const materials = [
  'Diamond', 'Emerald', 'Sapphire', 'Ruby', 'Amethyst', 'Beryl', 'Corundum',
  'Spinel', 'Topaz', 'Topaz', 'Opal', 'Jade', 'Aquamarine', 'Turquoise',
  'Lapis Lazuli', 'Quartz', 'Pearl', 'Garnet', 'Amber', 'Zircon', 'Iolite',
  'Citrine', 'Bloodstone', 'Carnelian', 'Agate', 'Bloodstone', 'Opal',
  'Hematite', 'Jacinth', 'Jasper', 'Malachite', 'Onyx', 'Peridot',
  'Rose Quartz', 'Brass', 'Copper', 'Iron', 'Steel', 'Silver', 'Gold',
  'Platinum', 'Obsidian', 'Onyx', 'Mithril', 'Adamantium', 'Bronze',
  'Titanium', 'Chain', 'Rock', 'Stone', 'Scalemail'
]

const items = [
  'cap',
  'skullcap',
  'headgear',
  'helm',
  'helmet',
  'coif',
  'crown',
  'circlet',
  'headdress',
  'helm',
  'helmet',
  'hat',
  'cap',
  'cap',
  'helm',
  'helmet',
  'headband',
  'coronet',
  'bonnet',
  'helmet',
  'helm',
  'visor',
  'monocle',
  'eyepatch',
  'patch',
  'earring',
  'mask',
  'veil',
  'jawbone',
  'pendant',
  'talisman',
  'torque',
  'circlet',
  'amulet',
  'chain',
  'choker',
  'neckclasp',
  'symbol',
  'trinket',
  'medallion',
  'collar',
  'necklace',
  'charm',
  'neckguard',
  'locket',
  'chestplate',
  'platemail',
  'cuirass',
  'breastplate',
  'brooch',
  'seal',
  'cloak',
  'shroud',
  'coat',
  'tunic',
  'cape',
  'shawl',
  'armbands',
  'bracelet',
  'wristguard',
  'gauntlets',
  'gloves',
  'buckler',
  'shield',
  'bullwhip',
  'cord',
  'boots',
]

const suffixes = [
  'the Void',
  'of Valor',
  'of Might',
  'of Defense',
  'of Fury',
  'of the Elders',
  'of the Ancients',
  'of Tranquility',
  'of Stability',
  'of Vindication',
  'of Devotion',
  'the Risen',
  'the Sun',
  'the Moon',
  'of Focus',
  'of Power',
  'the Savage',
  'the Destroyer',
  'the General',
  'Superiority',
  'Lamentation',
  'Destruction',
  'Defiance',
  'the Titan',
  'the Elements',
  'the Guardian',
  'Eradication',
  'Dawn',
  'Insight',
  'the Righteous',
  'the Storm',
  'the Dead',
  'the Sea',
  'the Ocean',
  'Protection',
  'the Protector',
  'the Master',
  'the Fall',
  'the Summer',
  'the Spring',
  'the Winter',
  'Ferocity',
  'Interpretation',
  'Serenity',
  'Warding',
  'Warfare',
  'Vigor',
  'Confusion',
  'Benevolence',
  'the Fearsome',
  'Control',
  'Peace',
  'Darkness',
  'Light',
  'Magnificence',
  'Empowerment',
  'Oblivion',
  'Blending',
  'Nirvana',
  'the Vortex',
  'Bewilderment',
  'Delight',
  'Woe',
  'Lies',
  'Time',
  'Wrath',
  'Compassion',
  'Harmony',
  'Brilliance',
  'the Jester',
  'Bedazzlement',
  'Kings',
  'Karma',
  'Nothingness',
  'Blackness',
  'Nature',
  'Striding',
  'Bone',
  'the Forest',
  'the Desert',
  'the Mountains',
  'the Swamp',
  'Fury',
  'the Shadow',
  'Rapture',
  'the Totem',
  'the Depths',
  'the Unicorn',
  'the Dragon',
  'the Demon',
  'Luck',
  'Mana',
  'Grandeur',
  'the Arcane',
  'the Spider',
  'the Wolf',
  'Night',
  'the Night',
  'the Day',
  'Day',
  'Regalia',
  'Melding',
  'Dislocation',
  'Resonance',
  'the Deranged',
  'Misdirection',
  'Recovery',
  'the Mystic',
  'Authority',
  'Glory',
  'Solidarity',
]

capitalize = function(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

class Artifact {
  constructor(opts) {
    return _.defaults(opts, {
      name: this.pickName(),
    })
  }

  pickName() {
    let name = capitalize(_.sample(items))

    // Add material
    if (Math.random() > 0.25) {
      name = _.sample(materials) + ' ' + name
    }

    // Add a prefix to name
    if (Math.random() > 0.25) {
      name = _.sample(prefixes) + ' ' + name
    }

    // Add a suffix
    if (Math.random() > 0.5) {
      name += ' ' + _.sample(suffixes)
    }

    return name
  }
}

module.exports = Artifact
